---
title: "R Notebook"
output: html_notebook
---


# load libraries
```{r}
library('stringr')
library('haven')
library('lme4')
library('lmerTest')
library('ggplot2')
library('psych')
library('rstatix')
library('sjPlot')
library('reshape2')
library('effectsize')
library('heplots')
```

# Open files
```{r}
clinical <- read_sav('./data/Final Dataset 4.11.21.sav')
clinical$Clinical_Trajectory <-  as.factor(clinical$Clinical_Trajectory)
clinical['sub'] <- sprintf("%04d", clinical$SubjectID)
clinical <- clinical[,c(ncol(clinical),1:(ncol(clinical)-1))]

aseg <- read.csv('./data/aseg_stats211222.txt', sep = '\t')
aseg_long <- aseg[grepl("long", aseg$Measure.volume),]
aseg_long['sub'] <- (str_split_fixed(aseg_long$Measure.volume, ".long.", 2)[,2])
aseg_long['time'] <- (str_split_fixed(aseg_long$Measure.volume, "_", 2)[,1])
aseg_long <- merge(aseg_long, clinical[,1:5], by='sub')

aseg_long <- aseg_long[c("sub", "Measure.volume", "Left.Hippocampus", "Left.Amygdala", 
                         "Right.Hippocampus", "Right.Amygdala", "EstimatedTotalIntraCranialVol", 
                         "time", "Clinical_Trajectory", "Gender", "Age")]


aseg_long_PTSD <- subset(aseg_long, Clinical_Trajectory != '1')
```

```{r}
T1_LA <- T1_LH <- T1_RA <- T1_RH <- 0
LA <- LH <- RA <- RH <- c()

for (i in c(1:nrow(aseg_long_PTSD))){
  if(aseg_long_PTSD$time[i] == 'T1'){
    T1_LA <- aseg_long_PTSD$Left.Amygdala[i]
    T1_LH <- aseg_long_PTSD$Left.Hippocampus[i]
    T1_RA <- aseg_long_PTSD$Right.Amygdala[i]
    T1_RH <- aseg_long_PTSD$Right.Hippocampus[i]
  }
  LA <- c(LA, T1_LA)
  LH <- c(LH, T1_LH)
  RA <- c(RA, T1_RA)
  RH <- c(RH, T1_RH)
}
aseg_long_PTSD['T1_LA'] <- LA
aseg_long_PTSD['T1_LH'] <- LH
aseg_long_PTSD['T1_RA'] <- RA
aseg_long_PTSD['T1_RH'] <- RH

aseg_long_PTSD_bl = aseg_long_PTSD[!grepl("T1", aseg_long_PTSD$time),]

```


```{r}
Model_LA_long <- lmer(Left.Amygdala ~ Clinical_Trajectory * time + T1_LA + Age + Gender + EstimatedTotalIntraCranialVol +(1|sub), data = aseg_long_PTSD_bl)

Model_RA_long <- lmer(Right.Amygdala ~ Clinical_Trajectory * time + T1_RA + Age + Gender + EstimatedTotalIntraCranialVol + (1|sub), data = aseg_long_PTSD_bl)

Model_LH_long <- lmer(Left.Hippocampus ~ Clinical_Trajectory * time + T1_LH + Age + Gender + EstimatedTotalIntraCranialVol + (1|sub), data = aseg_long_PTSD_bl)

Model_RH_long <- lmer(Right.Hippocampus ~ Clinical_Trajectory * time + T1_RH + Age + Gender + EstimatedTotalIntraCranialVol + (1|sub), data = aseg_long_PTSD_bl)
```

```{r}
summary(Model_LA_long)
summary(Model_RA_long)
summary(Model_LH_long)
summary(Model_RH_long)
```

```{r}

```

